export const CST = {
  SCENES: {
    LOAD: "LOAD",
    MENU: "MENU",
    PLAY: "PLAY",
    NEWGAME: "NEWGAME",
    JOINGAME: "JOINGAME",
  },

  IMAGES: {
    LOGO: "logo.png",
    LOGOBLACK: "logo_black.png",
    OPTSBTN: "options_button.png",
    PLAYBTN: "play_button.png",
    TITLEBG: "title_bg.jpg",
    TABLEBG: "table_bg.png",
  },

  CARDS: {
    S1: "ace_of_spades.png",
    S2: "2_of_spades.png",
    S3: "3_of_spades.png",
    S4: "4_of_spades.png",
    S5: "5_of_spades.png",
    S6: "6_of_spades.png",
    S7: "7_of_spades.png",
    S8: "8_of_spades.png",
    S9: "9_of_spades.png",
    S10: "10_of_spades.png",
    SJ: "jack_of_spades.png",
    SQ: "queen_of_spades.png",
    SK: "king_of_spades.png",

    H1: "ace_of_hearts.png",
    H2: "2_of_hearts.png",
    H3: "3_of_hearts.png",
    H4: "4_of_hearts.png",
    H5: "5_of_hearts.png",
    H6: "6_of_hearts.png",
    H7: "7_of_hearts.png",
    H8: "8_of_hearts.png",
    H9: "9_of_hearts.png",
    H10: "10_of_hearts.png",
    HJ: "jack_of_hearts.png",
    HQ: "queen_of_hearts.png",
    HK: "king_of_hearts.png",

    C1: "ace_of_clubs.png",
    C2: "2_of_clubs.png",
    C3: "3_of_clubs.png",
    C4: "4_of_clubs.png",
    C5: "5_of_clubs.png",
    C6: "6_of_clubs.png",
    C7: "7_of_clubs.png",
    C8: "8_of_clubs.png",
    C9: "9_of_clubs.png",
    C10: "10_of_clubs.png",
    CJ: "jack_of_clubs.png",
    CQ: "queen_of_clubs.png",
    CK: "king_of_clubs.png",

    D1: "ace_of_diamonds.png",
    D2: "2_of_diamonds.png",
    D3: "3_of_diamonds.png",
    D4: "4_of_diamonds.png",
    D5: "5_of_diamonds.png",
    D6: "6_of_diamonds.png",
    D7: "7_of_diamonds.png",
    D8: "8_of_diamonds.png",
    D9: "9_of_diamonds.png",
    D10: "10_of_diamonds.png",
    DJ: "jack_of_diamonds.png",
    DQ: "queen_of_diamonds.png",
    DK: "king_of_diamonds.png",
  },

  AUDIOS: {
    TITLEMUSIC: "shuinvy-childhood.mp3",
  },

  SPRITES: {
    CAT: "cat.png",
  },

  FRAMES: {
    32: { frameHeight: 32, frameWidth: 32 },
    64: { frameHeight: 64, frameWidth: 64 },
  },
};
